[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.filesystem = spiffs
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_LOOP_STACK_SIZE=8192
lib_deps =
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson@^6.21.6
